[package]
name = "securetar"
version = "0.1.0"
edition = "2024"
description = "Rust reader primitives for SecureTar v3 encrypted streams (used in Home Assistant backups)"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/orottier/securetar-rs"
repository = "https://github.com/orottier/securetar-rs"
documentation = "https://docs.rs/securetar"
keywords = ["securetar", "tar", "backup", "encryption", "home-assistant"]
categories = ["cryptography", "encoding"]
exclude = ["tests/fixtures/*"]

[lib]
name = "securetar"

[dependencies]
argon2 = "0.5.3"
blake2b_simd = "1.0.3"
sodiumoxide = "0.2.7"
thiserror = "2.0.12"
